### PR TITLE
adding pkgdown website

### PR DESCRIPTION
**Pull request by jebyrnes**
This pull request adds a pkgdown website for vegan, which the vegandevs can put up easily as a github.io site. These sites have been tremendously popular and ease new learners into the package. I've done the simplest thing possible, and just used pkgdown to generate the site from what is here, but with some slight re-organization and/or pulling examples from the web, this could turn into a really useful resource for the community.

It can also be incorporated into the package build scripts, and, heck, maybe it's time to add a Readme.md and a hex sticker. Give them away at ESA?

### CODE REVIEW

**Comment by psolymos** [comment]
IMO an automated build would be preferred. Here is an example using a build scrip on Travis and deploying to gh-pages branch. Needs a GitHub PAT for the person on behalf of whom the commit is made. 

https://github.com/psolymos/EDMAinR/blob/master/.travis.yml

This setup also requires to modify .Rbuildignore and README.md

**Comment by jebyrnes** [comment]
Good point. Easy enough to take the pull, then add something to the .travis.yml. Or I'm happy to do the work. LMK.

**Comment by gavinsimpson** [comment]
Thanks for this @jebyrnes. I think @psolymos @jarioksa and I should quickly decide what we want to do here; do we want the pkgdown site to show the current master branch or the current CRAN release branch, for example.

I'm fully in favour of having a pkgdown site for vegan; I use one for *gratia* and plan to add them to other packages I maintain as time permits. Also, Jari mentioned a little while back that some of the materials on his Oulu site might disappear now that he has "retired", and wondered what we might do about some of the extra things hosted there. Building them into the pkgdown site could also be an option.

Then automating this would be best. I know that we can deply pkgdown via the travis builds we already do, but there seems to be a move towards using GitHub Actions for similar CI/CD things, so I'd like to investigate that too before we settle on a final approach to automating this.

**Comment by jebyrnes** [comment]
Thanks, @gavinsimpson! The idea popped into my head the other week as I reviewed a new package for Methods in Ecology and Evolution and asked them to turn it into a pkgdown site (their appendices - five of 'em - were vignettes, and they had a Readme) - I just think it makes sense to put all of this into the long-term cycle of a package, if only for new learners who want to see how to use such a thing!

**Comment by psolymos** [comment]
@gavinsimpson @jarioksa : I am in favor of having a pkgdown site too. I used GitHub actions with success recently for [site deployment](https://github.com/borealbirds/borealbirds.github.io/blob/dev/.github/workflows/build.yml), but installing deps like rgl for this EDMAinR package proved to be more difficult in the absence of community resources so I gave up and went back to Travis.

**Comment by jarioksa** [comment]
@psolymos @gavinsimpson : I haven't followed this PR, and I still don't know what is this pkgdown. Anyway, I know nothing that speaks against having this, and I think the CRAN branch would be more meaningful to track there. On the other hand, CRAN branch can change: when the current development (master) is released as new major version 2.6-0, it will be branched to cran-2.6 and the current cran-2.5 branch will be abandoned. How this works with this system? (And I think it would make sense to move to 2.6 series in CRAN.)

**Comment by psolymos** [comment]
@jarioksa and @gavinsimpson I added the pkgdown documentation to my personal fork to see how it looks. It gives an idea but it would require some customization of the `_pkgdown.yml` file to get the vignettes where they belong. And a more descriptive `README.md` would also be helpful. See here: https://psolymos.github.io/vegan/ Let me know what you think.

**Comment by jebyrnes** [comment]
@jarioksa the site can be rebuilt at any point - so, when a new version gets sent to CRAN, the pkgdown site can be rebuilt simply with `pkgdown::build_site()` so that the site is always up to date.

**Comment by gavinsimpson** [comment]
To follow up on this, I spent a bit of time recently getting GitHub Actions to build a pkgdown site for vegan: https://vegandevs.github.io/vegan/

I have done *nothing* with it as yet to curate the Reference section into groups of associated functions (changes to `_pkgdown.yml` welcome, otherwise I'll start combining them into groups of functions).

It's also building from the master branch but as we're planning a 2.6.x release it will become the CRAN release, so perhaps this isn't so much of a problem?

**Comment by psolymos** [comment]
Hey @gavinsimpson thanks for adding the pkgdown pages, it is nice to see the output from all the examples. Grouping functions makes a lot of sense.

**Comment by gavinsimpson** [comment]
I'm going to close this PR as the pkgdown site is operating. I'll add the outstanding job of grouping functions in the Reference page output as a new issue.

**Pull request closed without merging**
