### PR TITLE
CLR did not use na.rm

### PR DESCRIPTION
**Pull request by TuomasBorman**

### CODE REVIEW

**Comment by TuomasBorman** [comment]
Fixing issue https://github.com/vegandevs/vegan/issues/661

**Comment by jarioksa** [comment]
Looks OK and safe, but do not change the DESCRIPTION: we change version numbers only at CRAN releases.

**Comment by jarioksa** [comment]
At closer look, there seems to be a deeper problem in  `"clr"`, `"alr"` and `"rclr"`. None of these passes `decostand(..., na.rm)` argument to the corresponding `.calc_*` function. Therefore user cannot set `na.rm` action, but the value `na.rm = TRUE`  of all `.calc_*` functions is _de facto_ hard-coded. What you found out was that this setting was not used in one case, but changing this won't allow users to set `na.rm`  in the `decostand` call (or `vegdist` call).

I won't merge this PR because much larger changes are needed to pass `decostand` and `vegdist` arguments.

**Comment by jarioksa** [comment]
I think that the problem is bigger than this one, but your fix will be a part of the solution even if larger changes are needed. Thanks for your contribution!

**Pull request merged**
