### PR TITLE
Aitchison

### PR DESCRIPTION
**Pull request by antagomir**
This solves the naming issue in #433 

Method names in `vegdist` are now changed from "aitchison" and "aitchison_robust" to "Aitchison" and "rAitchison", respectively.

In addition, I added the transformations "alr" and "ilr" due to recent requests. These were discussed in the original issue as well.

In addition, I updated unit tests for all these methods. The tests include also comparisons with alternative packages, to show the compatibility (those tests with external packages are commented out, though). 

Everything seems to work and properly tested, but cross-check always good.

### CODE REVIEW

**Comment by antagomir** [comment]
Woops, I had forgot to follow-up whether the automated builds go through. Tried to fix, hopefully all ok now and can be merged soon.

**Comment by antagomir** [comment]
All checks seem to pass now. Ok to merge?

**Comment by antagomir** [comment]
Is there anything else I could do more to get this approved?

**Comment by jarioksa** [comment]
Sorry for this. I have been busy with other packages (such as Hmsc) and I haven't had time to look at this. It is my unforgivable ignorance. I'll check the PR early next week (on Sunday you shan't work).

**Comment by gavinsimpson** [comment]
@antagomir A couple of things I noted:

1. Can you confirm that you are the original and *only* copyright holder of the code that you modified from the {mia} package?
2. Assuming 1., are you agreeing that the code can be released under the GPL as per vegan's license?

I note you are a contributor to the mia but it's not immediately clear who owns the specific code that was modified and included here. If you are the sole copyright holder, then assuming you agree to 2, this question is moot. If you aren't the sole copyright holder (i.e. if anyone modified the code you included here) then we have an issue of compatible licences (mia is Artistic) and we are likely violating the mia license as the copyright file is not included here in the PR.

3. I would recommend that we avoid method names that contained mixed case. None of the methods we currently support in `decostand` use anything but lower case or a period.

    I would suggest: `aitchison` and `robust.aitchison` if we aren't allowed underscores (I get Jari's objection but these are character strings not function names :p ).

**Comment by gavinsimpson** [comment]
Sorry - I too have been busy and meant to comment my 3. much earlier (though that is easily fixed via a patch to the code) but 1. ans 2. need addressing I believe (unless you know different @jarioksa ?)

**Comment by jarioksa** [comment]
I lightheartedly merged this, but @gavinsimpson was younger, aware and spick and span on legalities (thank you, Gav!). The rights and licensing issues are the most crucial ones: if they are not settled, I must revert the merge. All other things (naming, mixed cases) are lightweight and can be changed on a whim.

**Comment by antagomir** [comment]
The PR #498 renames ```aitchison``` and ```robust.aitchison``` as suggested.

License:

1. I can confirm that me (Leo Lahti @antagomir), Tuomas Borman (@TuomasBorman), and Felix M. Ernst (@FelixErnst) are the original and only copyright holders of the code that I transferred here from the {mia} package. We are also the main developers of that package.

2. We agree that the code can be released under the GPL as per vegan's license. TB and FE have expressed their approval in [mia issue #125](https://github.com/microbiome/mia/issues/125). 

I could not trace back all origins of the ILR code to confirm GPL2, and the ILR implementation was also otherwise slow. Hence removed all ILR related parts that were in my earlier PR.

**Comment by gavinsimpson** [comment]
@antagomir Thanks for this.

Sorry to be a pain, but could @TuomasBorman and @FelixErnst also indicate *here* (via a comment) their agreement to our releasing the relevant code under GPL-2, that would be best (just in case someone deletes the {mia} repo for example...).

**Comment by antagomir** [comment]
Sure.

**Comment by FelixErnst** [comment]
Agreement from my side as well.

**Comment by antagomir** [comment]
Thanks both. I wish we could proceed with this again :-)

**Comment by jarioksa** [comment]
Yep, it was merged – and it will stay merged. Next release.

**Pull request merged**
