### PR TITLE
Aitchison

### PR DESCRIPTION
**Pull request by antagomir**
Summary of this PR:

1) Switches to the suggested naming in [#460](https://github.com/vegandevs/vegan/pull/460) ie. "aitchison" and "robust.aitchison"

2) Removes ILR related parts that were in my earlier PR as the implementation was also simple and unoptimized. Better to add ILR more properly if a need will arise.

3) Updated tests and documentation accordingly w.r.t. 1-2

I think this PR should resolve all the remaining issues that there were.

### CODE REVIEW

**Comment by antagomir** [comment]
This PR adds to #460

**Comment by gavinsimpson** [comment]
Just following up on this; does this need merging in addition to #460 ? The comment by @antagomir suggests it is but I lost track of these things.

**Comment by antagomir** [comment]
Yes it does. This includes changes that were requested after merging #460

**Comment by gavinsimpson** [comment]
Ah, OK, apologies for not noticing that. We'll take a look at get this merged ASAP (it doesn't appear to be causing any problems with our checks)

**Comment by gavinsimpson** [comment]
Everything looked fine; merged. Thanks @antagomir for these contributions and for bearing with us getting the "t"s crossed and the "i"s dotted.

**Pull request merged**
