### PR TITLE
Parallel version of cascadeKM

### PR DESCRIPTION
**Pull request by becarioprecario**
Hi,

I have just modified the cascadeKM function to support parallel computing. It should work both on Unix (via mclapply) and Windows (via parLapply). 

Best,

Virgilio

### CODE REVIEW

**Comment by jarioksa** [comment]
Thanks for this work. However, its user interface does not accord to **vegan** conventions –  see `vignette("decision-vegan", package="vegan")`. What do you think about this? Would it be feasible to implement with our conventions?

**Comment by becarioprecario** [comment]
Thanks for this work. However, its user interface does not accord to vegan conventions – see vignette("decision-vegan", package="vegan"). What do you think about this? Would it be feasible to implement with our conventions?

Yes. I could add a ‘parallel = getOption("mc.cores")’ argument to the function and then handle parallel computing for unix and windows depending on its value. Will that be fine?

**Comment by becarioprecario** [comment]
Please, could you check that my latest modifications comply with your conventions?

**Comment by becarioprecario** [comment]
@jarioksaplease, could you check that my latest changes follow the **vegan** convention and that it can be merged into the main repository? If not, I can make any required modifications.

**Comment by jarioksa** [comment]
The implementation does not conform with the standard as described in the vignette on design-decisions, but I'll fix that after this merge. For instance, the numeric value of `parallel` will be ignored in unix-like systems, and user-supplied `makeCluster()` cluster will be ignored in unix-like systems and destroyed after use in Windows.

**Comment by jarioksa** [comment]
@becarioprecario I added your name in the Authors filed in man/cascadeKM.Rd. That is OK? And also check the form I used.

**Comment by becarioprecario** [comment]
@jarioksa yes, many thanks for checking and fixing my pull request and for adding my name to the Authors (maybe use V. Gomez-Rubio, orchid 0000-0002-4791-3072 if needed).

**Pull request merged**
